using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Splil : MonoBehaviour
{
    [SerializeField] private float Speed;
    private void OnTriggerEnter(Collider other)
    {
        if(other.gameObject.layer == LayerMask.NameToLayer("Player"))
        {
            Debug.Log("╚„Ų«");
            //Destroy(gameObject);
        }
        else if(other.gameObject.layer == LayerMask.NameToLayer("Wall"))
        {
            //Destroy(gameObject);
        }
    }
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        transform.position += transform.forward * Time.deltaTime * Speed;
    }
}
